---
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: io1-csi
provisioner: ebs.csi.aws.com
parameters:
  allowAutoIOPSPerGBIncrease: 'true'
  iopsPerGB: '50'
  type: io1
reclaimPolicy: Delete
allowVolumeExpansion: true
volumeBindingMode: WaitForFirstConsumer
