apiVersion: v1
kind: Pod
metadata:
  name: check-pv
spec:
  volumes:
  - name: volume-to-test
    persistentVolumeClaim:
      claimName: volume-to-test-pvc  
  containers:
  - name: bash
    image: registry.redhat.io/openshift4/ose-tools-rhel8
    command: [ "/bin/bash", "-c", "--" ]
    args: [ "while true; do sleep 30; done;" ]
    volumeMounts:
      - name: volume-to-test
        mountPath: /volume-test
