apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: vol-to-test-4k-pv-claim
  namespace: fio-perf-test
spec:
  storageClassName: ocs-storagecluster-ceph-rbd
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi